### ISSUE TITLE
Wound Threshold penalty applies twice on skill checks

### ISSUE THREAD

**Issue by blackanthrax** [Roll20-Pathfinder-Character-Sheet/Roll20-Pathfinder-Character-Sheet#184]
as described in https://github.com/Roll20/roll20-character-sheets/issues/3190

**Comment by vince-roll20** [comment]
I'm not able to reproduce this.  The skill total adjusts properly as the wound threshold changes.  Would you mind importing a character with this issue into the PF beta test game? https://app.roll20.net/join/801350/kEQ72w

**Comment by vince-roll20** [comment]
If you reset one of your skill macros (just delete the text, it will auto-populate when changing fields).  See if that fixes the issue.

**Comment by blackanthrax** [comment]
Hi Vince, 
i just realized that you answered to that issue here. Since i got no notification.
currently i can't import a character to the test game, since the roll20 vault seems to be broken.

But your last comment seems to be working. thanks!
