### ISSUE TITLE
Question : Building/Testing build in roll20

### ISSUE THREAD

**Issue by Narolas** [Roll20-Pathfinder-Character-Sheet/Roll20-Pathfinder-Character-Sheet#206]
I apologize if the answer is obvious, but I'm not sure how to actually deploy this and test it.
I built the latest master commit, then put the resulting index.html in the "HTML Layout" of a custom sheet on a Roll20 campaign, but I'm clearly missing something, the resulting character sheet is one long broken page. Seems like my build is missing things, but I get no errors and I followed the README guide to make sure I wasn't missing something obvious.

Is there a specific way to build/deploy this? Is it required to build this with Visual Studio Code (I'm on Webstorm, but I don't see why webpack would build it differently)?

**Comment by vince-roll20** [comment]
I'm not exactly sure...  ;-(  Chris B. set this up initially.
You should be able to build an index file that includes the sheetworker script.
I'm using vsc and use the command "npm run build" from terminal within the "src" folder to create a fully functional index.html from the various .js files and index.html(sans sheetworker code).

**Comment by Narolas** [comment]
With npm run build or prod, at the folder root or in /src, it generates an index.html (which seems to contain the js at the end), and an index.js separately. 
The built index.html still had the 
 
comment at the start.

Is the resulting character sheet (as seen in the "Preview" tab) supposed to look like this?
https://imgur.com/j94gv4n

I'm assuming I only need to paste the index.html file in the "HTML Layout" tab and nothing else.

**Comment by vince-roll20** [comment]
Are you also using the css and translation file?  You'll need all three.  The "<--Development..." is normal for npm run build.  We use "npm prod build" when we submit to roll20's repo.

**Comment by vince-roll20** [comment]
My bad. I stated the wrong command for production. You have it correct "npm run prod"  I normally remove the development comment from the "working" code base before a use "npm run prod".  The development comment actually has no impact on the rendered/finished code.  
Compiling an index.html file that includes a single line of js(sheetworker script) is exactly what you should get.  You will need to also include the css and translation file in roll20's game settings sheet editor if you want to view the sheet as intended in-game.

**Comment by Narolas** [comment]
Oh, I really thought I was doing something wrong. I completely missed that you need to copy the contents of the pathfinder.css and translate.json files, sorry for bothering you, I feel damn silly.

**Comment by vince-roll20** [comment]
Cool Beans.
