### ISSUE TITLE
@{armor3-max-dex} not taken into account when Carrying Capacity is set to "ignore"

### ISSUE THREAD

**Issue by EtienneLamoureux** [Roll20-Pathfinder-Character-Sheet/Roll20-Pathfinder-Character-Sheet#223]
## Problem
When an equipped armor with less `@{armor3-max-dex}` than `@{DEX-mod}` is equipped, DEX to AC is not reduced

## Reproduction steps
1. Create a new character
2. Have 12 DEX
3. Go to the equipment tab
2. Create an armor with 0 AC and 0 max dex
3. Click the `@{set-as-armor}` button
4. Go to the defence tab
5. Validate that the equipped armour allows 0 max dex (`@{armor3-max-dex}` = 0)
6. `@{AC}` will be 11, should be 10

**Comment by vince-roll20** [comment]
HI Etienne,
once you choose one of the encumbrance options that ignores armor and shield, max dex no longer applies on the sheet.

**Comment by EtienneLamoureux** [comment]
> 
> 
> HI Etienne,
> once you choose one of the encumbrance options that ignores armor and shield, max dex and acp no longer applies on the sheet.

That makes sense I guess. Thanks for the timely answer!
